module.exports = function (self) {
	return [
		{
			type: 'static-text',
			id: 'info',
			width: 12,
			label: 'Information',
			value: 'This module creates a new api.video live stream and adds restream destinations for Facebook and/or Youtube.',
		},
		{
			type: 'textinput',
			id: 'apivideo_api_key',
			label: 'api.video API Key',
			width: 12,
			required: false,
			tooltip: 'Your api.video API key (found in your api.video dashboard). Required for creating streams.',
		},
		{
			type: 'checkbox',
			id: 'enable_facebook_restream',
			label: 'Enable Facebook Restream',
			width: 6,
			default: false,
			tooltip: 'Enable restreaming to Facebook Live',
		},
		{
			type: 'checkbox',
			id: 'enable_youtube_restream',
			label: 'Enable Youtube Restream',
			width: 6,
			default: false,
			tooltip: 'Enable restreaming to Youtube Live',
		},
		{
			type: 'textinput',
			id: 'fb_page_id',
			label: 'Facebook Page ID',
			width: 6,
			required: false,
			tooltip: 'The numeric ID of your Facebook Page (required if Facebook restream is enabled)',
		},
		{
			type: 'textinput',
			id: 'fb_user_token',
			label: 'Facebook User Access Token',
			width: 12,
			required: false,
			tooltip: 'User Access Token with publish_video permission (required if Facebook restream is enabled)',
		},
		{
			type: 'textinput',
			id: 'fb_app_id',
			label: 'Facebook App ID',
			width: 6,
			required: false,
			tooltip: 'Your Facebook App ID (optional, for token extension)',
		},
		{
			type: 'textinput',
			id: 'fb_app_secret',
			label: 'Facebook App Secret',
			width: 6,
			required: false,
			tooltip: 'Your Facebook App Secret (optional, for token extension)',
		},
		{
			type: 'textinput',
			id: 'yt_rtmp_url',
			label: 'Youtube RTMP URL',
			width: 12,
			required: false,
			tooltip: 'Youtube Live RTMP server URL (e.g., rtmp://a.rtmp.youtube.com/live2) - required if Youtube restream is enabled',
		},
		{
			type: 'textinput',
			id: 'yt_stream_key',
			label: 'Youtube Stream Key',
			width: 12,
			required: false,
			tooltip: 'Your Youtube Live stream key - required if Youtube restream is enabled',
		},
	]
}
